// Type augmentation for @arco-design/web-vue/es/icon
// vue-tsc sometimes fails to resolve individual icon re-exports from the barrel .d.ts
// This file provides direct type declarations for icons used across the project.
// Build (vite) is not affected — only vue-tsc type checking.

declare module '@arco-design/web-vue/es/icon' {
  import type { DefineComponent } from 'vue';

  type ArcoIcon = DefineComponent<{
    size?: number | string;
    strokeWidth?: number;
    strokeLinecap?: string;
    strokeLinejoin?: string;
    rotate?: number;
    spin?: boolean;
  }>;

  // Directional
  export const IconArrowDown: ArcoIcon;
  export const IconArrowFall: ArcoIcon;
  export const IconArrowLeft: ArcoIcon;
  export const IconArrowRight: ArcoIcon;
  export const IconArrowRise: ArcoIcon;
  export const IconArrowUp: ArcoIcon;
  export const IconCaretDown: ArcoIcon;
  export const IconCaretLeft: ArcoIcon;
  export const IconCaretRight: ArcoIcon;
  export const IconCaretUp: ArcoIcon;
  export const IconDoubleDown: ArcoIcon;
  export const IconDoubleLeft: ArcoIcon;
  export const IconDoubleRight: ArcoIcon;
  export const IconDoubleUp: ArcoIcon;
  export const IconDown: ArcoIcon;
  export const IconDownCircle: ArcoIcon;
  export const IconDragArrow: ArcoIcon;
  export const IconExpand: ArcoIcon;
  export const IconLeft: ArcoIcon;
  export const IconLeftCircle: ArcoIcon;
  export const IconMenuFold: ArcoIcon;
  export const IconMenuUnfold: ArcoIcon;
  export const IconRight: ArcoIcon;
  export const IconRightCircle: ArcoIcon;
  export const IconRotateLeft: ArcoIcon;
  export const IconRotateRight: ArcoIcon;
  export const IconShrink: ArcoIcon;
  export const IconSwap: ArcoIcon;
  export const IconToBottom: ArcoIcon;
  export const IconToLeft: ArcoIcon;
  export const IconToRight: ArcoIcon;
  export const IconToTop: ArcoIcon;
  export const IconUp: ArcoIcon;
  export const IconUpCircle: ArcoIcon;

  // Status / Feedback
  export const IconCheck: ArcoIcon;
  export const IconCheckCircle: ArcoIcon;
  export const IconCheckCircleFill: ArcoIcon;
  export const IconCheckSquare: ArcoIcon;
  export const IconClockCircle: ArcoIcon;
  export const IconClose: ArcoIcon;
  export const IconCloseCircle: ArcoIcon;
  export const IconCloseCircleFill: ArcoIcon;
  export const IconExclamation: ArcoIcon;
  export const IconExclamationCircle: ArcoIcon;
  export const IconExclamationCircleFill: ArcoIcon;
  export const IconExclamationPolygonFill: ArcoIcon;
  export const IconInfo: ArcoIcon;
  export const IconInfoCircle: ArcoIcon;
  export const IconInfoCircleFill: ArcoIcon;
  export const IconMinus: ArcoIcon;
  export const IconMinusCircle: ArcoIcon;
  export const IconMinusCircleFill: ArcoIcon;
  export const IconPlus: ArcoIcon;
  export const IconPlusCircle: ArcoIcon;
  export const IconPlusCircleFill: ArcoIcon;
  export const IconQuestion: ArcoIcon;
  export const IconQuestionCircle: ArcoIcon;
  export const IconQuestionCircleFill: ArcoIcon;
  export const IconStop: ArcoIcon;

  // Rating
  export const IconHeart: ArcoIcon;
  export const IconHeartFill: ArcoIcon;
  export const IconStar: ArcoIcon;
  export const IconStarFill: ArcoIcon;
  export const IconThumbDown: ArcoIcon;
  export const IconThumbDownFill: ArcoIcon;
  export const IconThumbUp: ArcoIcon;
  export const IconThumbUpFill: ArcoIcon;

  // Operation
  export const IconAt: ArcoIcon;
  export const IconCloud: ArcoIcon;
  export const IconCloudDownload: ArcoIcon;
  export const IconCode: ArcoIcon;
  export const IconCodeBlock: ArcoIcon;
  export const IconCodeSquare: ArcoIcon;
  export const IconCustomerService: ArcoIcon;
  export const IconDownload: ArcoIcon;
  export const IconExport: ArcoIcon;
  export const IconEye: ArcoIcon;
  export const IconEyeInvisible: ArcoIcon;
  export const IconHistory: ArcoIcon;
  export const IconHome: ArcoIcon;
  export const IconImport: ArcoIcon;
  export const IconLaunch: ArcoIcon;
  export const IconList: ArcoIcon;
  export const IconMessage: ArcoIcon;
  export const IconMessageBanned: ArcoIcon;
  export const IconMore: ArcoIcon;
  export const IconMoreVertical: ArcoIcon;
  export const IconPoweroff: ArcoIcon;
  export const IconRefresh: ArcoIcon;
  export const IconReply: ArcoIcon;
  export const IconSave: ArcoIcon;
  export const IconScan: ArcoIcon;
  export const IconSearch: ArcoIcon;
  export const IconSelectAll: ArcoIcon;
  export const IconSend: ArcoIcon;
  export const IconSettings: ArcoIcon;
  export const IconShareAlt: ArcoIcon;
  export const IconShareExternal: ArcoIcon;
  export const IconShareInternal: ArcoIcon;
  export const IconSync: ArcoIcon;
  export const IconTranslate: ArcoIcon;
  export const IconUpload: ArcoIcon;
  export const IconVoice: ArcoIcon;

  // Text editing
  export const IconAlignCenter: ArcoIcon;
  export const IconAlignLeft: ArcoIcon;
  export const IconAlignRight: ArcoIcon;
  export const IconAttachment: ArcoIcon;
  export const IconBgColors: ArcoIcon;
  export const IconBold: ArcoIcon;
  export const IconBrush: ArcoIcon;
  export const IconCopy: ArcoIcon;
  export const IconDelete: ArcoIcon;
  export const IconEdit: ArcoIcon;
  export const IconEraser: ArcoIcon;
  export const IconFilter: ArcoIcon;
  export const IconFindReplace: ArcoIcon;
  export const IconFontColors: ArcoIcon;
  export const IconFormula: ArcoIcon;
  export const IconH1: ArcoIcon;
  export const IconH2: ArcoIcon;
  export const IconH3: ArcoIcon;
  export const IconH4: ArcoIcon;
  export const IconH5: ArcoIcon;
  export const IconH6: ArcoIcon;
  export const IconH7: ArcoIcon;
  export const IconHighlight: ArcoIcon;
  export const IconItalic: ArcoIcon;
  export const IconLineHeight: ArcoIcon;
  export const IconLink: ArcoIcon;
  export const IconObliqueLine: ArcoIcon;
  export const IconOrderedList: ArcoIcon;
  export const IconOriginalSize: ArcoIcon;
  export const IconPaste: ArcoIcon;
  export const IconQuote: ArcoIcon;
  export const IconRedo: ArcoIcon;
  export const IconScissor: ArcoIcon;
  export const IconSort: ArcoIcon;
  export const IconSortAscending: ArcoIcon;
  export const IconSortDescending: ArcoIcon;
  export const IconStrikethrough: ArcoIcon;
  export const IconUnderline: ArcoIcon;
  export const IconUndo: ArcoIcon;
  export const IconUnorderedList: ArcoIcon;

  // Media
  export const IconCamera: ArcoIcon;
  export const IconFaceFrownFill: ArcoIcon;
  export const IconFaceMehFill: ArcoIcon;
  export const IconFaceSmileFill: ArcoIcon;
  export const IconMute: ArcoIcon;
  export const IconPause: ArcoIcon;
  export const IconPauseCircle: ArcoIcon;
  export const IconPlayArrow: ArcoIcon;
  export const IconPlayCircle: ArcoIcon;
  export const IconRecord: ArcoIcon;
  export const IconRecordStop: ArcoIcon;
  export const IconSkipNext: ArcoIcon;
  export const IconSkipPrevious: ArcoIcon;
  export const IconSound: ArcoIcon;
  export const IconSoundFill: ArcoIcon;

  // File / Directory
  export const IconCommonFile: ArcoIcon;
  export const IconFile: ArcoIcon;
  export const IconFileAudio: ArcoIcon;
  export const IconFileImage: ArcoIcon;
  export const IconFilePdf: ArcoIcon;
  export const IconFileVideo: ArcoIcon;
  export const IconFolder: ArcoIcon;
  export const IconFolderAdd: ArcoIcon;
  export const IconFolderDelete: ArcoIcon;

  // Object / Data
  export const IconBook: ArcoIcon;
  export const IconBookmark: ArcoIcon;
  export const IconBulb: ArcoIcon;
  export const IconCalendar: ArcoIcon;
  export const IconCalendarClock: ArcoIcon;
  export const IconCelsius: ArcoIcon;
  export const IconChart: ArcoIcon;
  export const IconChartBar: ArcoIcon;
  export const IconChartLine: ArcoIcon;
  export const IconChartPie: ArcoIcon;
  export const IconClock: ArcoIcon;
  export const IconCommand: ArcoIcon;
  export const IconComputer: ArcoIcon;
  export const IconCopyright: ArcoIcon;
  export const IconDashboard: ArcoIcon;
  export const IconDesktop: ArcoIcon;
  export const IconDice: ArcoIcon;
  export const IconDragDot: ArcoIcon;
  export const IconDragDotVertical: ArcoIcon;
  export const IconDriveFile: ArcoIcon;
  export const IconEar: ArcoIcon;
  export const IconEmail: ArcoIcon;
  export const IconEmpty: ArcoIcon;
  export const IconExperiment: ArcoIcon;
  export const IconFire: ArcoIcon;
  export const IconGift: ArcoIcon;
  export const IconIdcard: ArcoIcon;
  export const IconImage: ArcoIcon;
  export const IconImageClose: ArcoIcon;
  export const IconInteraction: ArcoIcon;
  export const IconLanguage: ArcoIcon;
  export const IconLayers: ArcoIcon;
  export const IconLayout: ArcoIcon;
  export const IconLoading: ArcoIcon;
  export const IconLocation: ArcoIcon;
  export const IconLock: ArcoIcon;
  export const IconLoop: ArcoIcon;
  export const IconMan: ArcoIcon;
  export const IconMenu: ArcoIcon;
  export const IconMindMapping: ArcoIcon;
  export const IconMobile: ArcoIcon;
  export const IconMoon: ArcoIcon;
  export const IconMosaic: ArcoIcon;
  export const IconNav: ArcoIcon;
  export const IconNotification: ArcoIcon;
  export const IconNotificationClose: ArcoIcon;
  export const IconPalette: ArcoIcon;
  export const IconPen: ArcoIcon;
  export const IconPhone: ArcoIcon;
  export const IconPrinter: ArcoIcon;
  export const IconPublic: ArcoIcon;
  export const IconPushpin: ArcoIcon;
  export const IconQrcode: ArcoIcon;
  export const IconRelation: ArcoIcon;
  export const IconRobot: ArcoIcon;
  export const IconRobotAdd: ArcoIcon;
  export const IconSafe: ArcoIcon;
  export const IconSchedule: ArcoIcon;
  export const IconShake: ArcoIcon;
  export const IconSkin: ArcoIcon;
  export const IconStamp: ArcoIcon;
  export const IconStorage: ArcoIcon;
  export const IconSubscribe: ArcoIcon;
  export const IconSubscribeAdd: ArcoIcon;
  export const IconSubscribed: ArcoIcon;
  export const IconSun: ArcoIcon;
  export const IconTag: ArcoIcon;
  export const IconTags: ArcoIcon;
  export const IconThunderbolt: ArcoIcon;
  export const IconTool: ArcoIcon;
  export const IconTrophy: ArcoIcon;
  export const IconUnlock: ArcoIcon;
  export const IconUser: ArcoIcon;
  export const IconUserAdd: ArcoIcon;
  export const IconUserGroup: ArcoIcon;
  export const IconVideoCamera: ArcoIcon;
  export const IconWifi: ArcoIcon;
  export const IconWoman: ArcoIcon;
}
