/** Arco Design 图标组件（动态渲染用） */
declare module '@arco-design/web-vue/es/icon' {
  import type { DefineComponent } from 'vue'
  export const IconDashboard: DefineComponent
  export const IconApps: DefineComponent
  export const IconSettings: DefineComponent
  export const IconStorage: DefineComponent
  export const IconCheckCircle: DefineComponent
  export const IconBook: DefineComponent
  export const IconSwap: DefineComponent
  export const IconCalendar: DefineComponent
  export const IconTool: DefineComponent
  export const IconSearch: DefineComponent
  export const IconNotification: DefineComponent
  export const IconExport: DefineComponent
  export const IconUser: DefineComponent
  export const IconArchive: DefineComponent
  export const IconClose: DefineComponent
  export const IconTags: DefineComponent
  export const IconBranch: DefineComponent
  export const IconSync: DefineComponent
  export const IconEdit: DefineComponent
  export const IconCode: DefineComponent
  export const IconFile: DefineComponent
  export const IconInteraction: DefineComponent
  export const IconLoading: DefineComponent
  export const IconHistory: DefineComponent
  export const IconComputer: DefineComponent
  export const IconList: DefineComponent
  export const IconHome: DefineComponent
  export const IconScan: DefineComponent
  export const IconCommand: DefineComponent
  export const IconSafe: DefineComponent
  export const IconRecord: DefineComponent
  export const IconCloseCircle: DefineComponent
  export const IconSkin: DefineComponent
  export const IconThunderbolt: DefineComponent
  export const IconBulb: DefineComponent
  export const IconPublic: DefineComponent
  export const IconStamp: DefineComponent
  export const IconUserGroup: DefineComponent
  export const IconDriveFile: DefineComponent
  export const IconUndo: DefineComponent
  export const IconDoubleDown: DefineComponent
  export const IconDoubleUp: DefineComponent
  export const IconBarChart: DefineComponent
  export const IconMessage: DefineComponent
  export const IconDownload: DefineComponent
  export const IconRelation: DefineComponent
  export const IconLayout: DefineComponent
  export const IconSchedule: DefineComponent
  export const IconCommon: DefineComponent
  export const IconLanguage: DefineComponent
}
