export const EventTypes = {
  // PLM
  MATERIAL_CREATED: 'MATERIAL_CREATED',
  BOM_REVISED: 'BOM_REVISED',
  BOM_ACTIVATED: 'BOM_ACTIVATED',
  ROUTING_REVISED: 'ROUTING_REVISED',
  // PLM → MES (ECN 执行完成)
  ECN_EXECUTED: 'ECN_EXECUTED',
  // SCM
  PURCHASE_ORDER_APPROVED: 'PURCHASE_ORDER_APPROVED',
  RECEIPT_CONFIRMED: 'RECEIPT_CONFIRMED',
  RECEIPT_PO_UPDATE_REQUEST: 'RECEIPT_PO_UPDATE_REQUEST', // SCM 内部：收货确认后更新 PO 收货数量
  // ERP
  SALES_ORDER_CONFIRMED: 'SALES_ORDER_CONFIRMED',
  // APS → MES
  WORK_ORDER_RELEASED: 'WORK_ORDER_RELEASED',
  // MES
  PRODUCTION_STARTED: 'PRODUCTION_STARTED',
  PRODUCTION_COMPLETED: 'PRODUCTION_COMPLETED',
  MATERIAL_ISSUE_REQUEST: 'MATERIAL_ISSUE_REQUEST',
  // WMS
  MATERIAL_ISSUED: 'MATERIAL_ISSUED',
  STOCK_IN_COMPLETED: 'STOCK_IN_COMPLETED',
  // QMS
  INSPECTION_TRIGGERED: 'INSPECTION_TRIGGERED',
  INSPECTION_COMPLETED: 'INSPECTION_COMPLETED',
  // EAM
  EQUIPMENT_STATUS_CHANGED: 'EQUIPMENT_STATUS_CHANGED',
  EQUIPMENT_FAILURE_REPORTED: 'EQUIPMENT_FAILURE_REPORTED',
  // MES → 自动入库编排
  OPERATION_COMPLETED: 'OPERATION_COMPLETED',
  WORK_ORDER_ALL_COMPLETED: 'WORK_ORDER_ALL_COMPLETED',
  FQC_INSPECTION_REQUEST: 'FQC_INSPECTION_REQUEST',
  PRODUCTION_RECEIPT_REQUEST: 'PRODUCTION_RECEIPT_REQUEST',
  WO_RECEIPT_WRITEBACK: 'WO_RECEIPT_WRITEBACK',
  // MES 父子工单联动
  CHILD_WO_COMPLETED: 'CHILD_WO_COMPLETED',
  WO_CANCELLED: 'WO_CANCELLED',
  // Outsourcing → WMS/QMS
  OUTSOURCING_ISSUE_CONFIRMED: 'OUTSOURCING_ISSUE_CONFIRMED',
  OUTSOURCING_RECEIPT_CONFIRMED: 'OUTSOURCING_RECEIPT_CONFIRMED',
  // WMS → Outsourcing
  OUTSOURCING_RECEIPT_STOCKED: 'OUTSOURCING_RECEIPT_STOCKED',
  // Outsourcing → SCM
  OUTSOURCING_SETTLEMENT_APPROVED: 'OUTSOURCING_SETTLEMENT_APPROVED',
  // SCM → Outsourcing
  OUTSOURCING_PAYABLE_CREATED: 'OUTSOURCING_PAYABLE_CREATED',
  // HR（技能认证变更，MES 可订阅用于缓存失效）
  CERTIFICATION_UPDATED: 'CERTIFICATION_UPDATED',
  // MES → HR（报工完成，HR 订阅汇总工时）
  OPERATION_REPORTED: 'OPERATION_REPORTED',
  // Traceability → WMS（召回冻结请求）
  RECALL_FREEZE_REQUEST: 'RECALL_FREEZE_REQUEST',
  // WMS → Traceability（召回冻结完成）
  RECALL_FREEZE_COMPLETED: 'RECALL_FREEZE_COMPLETED',
} as const;

export type EventType = (typeof EventTypes)[keyof typeof EventTypes];
